import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head children={undefined}></Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
