import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const inter = Poppins({weight:"500",
style:['italic'],
subsets:["latin"]});

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayer({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
